name: adivinador de numeros
description: just a game thats guess the number you think.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  provider: ^6.0.1
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: mainFont
      fonts:
        - asset: assets/fonts/IMFellEnglishSC-Regular.ttf

flutter_native_splash: # comandos para crear la splash screen: flutter clean / flutter pub get/ flutter pub run flutter_native_splash:create
  background_image: "assets/100.png"
  android: true
  ios: true
  web: true

flutter_icons: # comando para actualizar el icono:flutter pub run flutter_launcher_icons:main
  image_path: "assets/100.png"
  android: true
  ios: true
